#!/bin/bash
#----------------------------------------------------------------------------
# This script mounts your remote share with basic options.                   |
# Just define the remote you wish to mount as well as the local mountpoint.  |
# The script will create a folder at the mountpoint                          |
#----------------------------------------------------------------------------

# Local mountpoint
mntpoint="/local/path" 		# It's recommended to mount your remote share in /mnt/disks/subfolder - 
                                # This is the only way to make it accesible to dockers

# Remote share
remoteshare="remote:path" 	# If you want to share the root of your remote share you have to 
                                # define it as "remote:" eg. "acd:" or "gdrive:" 


#---------------------------------------------------------------------------------------------------------------------


mkdir -p $mntpoint
rclone mount --max-read-ahead 1024k --allow-other $remoteshare $mntpoint &
